### ISSUE TITLE
Make ShapeFile Draw Mask Cache

### ISSUE THREAD

**Issue by racerxdl** [opensatelliteproject/goesdump#56]
Currently OSP can draw shapefiles in _all_ images, but it takes lots of time for full disks ( > 10 seconds ), so we need to figure out a way to cache the overlays.

**Comment by n2cr** [comment]
As an interim fix could you make a standalone executable?  It could even be run on another system with network access to the PNG files.  This will have minimum impact on the real-time demod/decode.

**Comment by racerxdl** [comment]
Not sure if understood what you want @n2cr. What do you mean standalone executable?

**Comment by n2cr** [comment]
Sorry.  A separate executable program which could be called from the command line and would take the path/filename of an existing PNG file and generate a file with the overlay.

**Comment by racerxdl** [comment]
Ahh sure, thats not hard to do. Let me add to the issues.

**Comment by racerxdl** [comment]
Ah actually, thats actually hard to do. Since the PNG file doesn't have (yet) the data for mapping coordinates.

**Comment by racerxdl** [comment]
Even without the cache generation, the generate times seens ok. Some samples of generated images

![image](https://user-images.githubusercontent.com/578310/28256240-a9ba26c2-6a96-11e7-8a6d-8a280d960001.png)
![image](https://user-images.githubusercontent.com/578310/28256246-b9ebb6d2-6a96-11e7-8329-84c92f113ef2.png)
![image](https://user-images.githubusercontent.com/578310/28256248-c18a8ea4-6a96-11e7-9602-f00a0a419a25.png)
![image](https://user-images.githubusercontent.com/578310/28256261-e8a1bb0c-6a96-11e7-8ca9-481179170c66.png)
![image](https://user-images.githubusercontent.com/578310/28256263-f3c25276-6a96-11e7-9b4a-db45b205a11b.png)

**Comment by racerxdl** [comment]
![image](https://user-images.githubusercontent.com/578310/28399565-3ce2dca6-6ce4-11e7-8615-5c1fd37ad4d3.png)

Configurable Thickness and Color. Separated enable for Lat/Lon Lines and Map
