### ISSUE TITLE
Add new false color LUT from hdoverobinson

### ISSUE THREAD

**Issue by n2cr** [opensatelliteproject/goesdump#90]
As described in [https://wx-star.com/post/169608535305/designing-false-colors-for-goes-r-hrit](https://wx-star.com/post/169608535305/designing-false-colors-for-goes-r-hrit),  hdoverobinson has created an improved false color look-up table (LUT) for GOES-R.

Modify XRIT to either replace the existing LUT or to provide an option allowing the user to select the LUT to be used in generating false color images.

**Comment by hdoverobinson** [comment]
The blog post does not go into so much detail but the user may recompile goesdump by replacing the LUT at goesdump/XRIT/LUT/falsecolor.png. For the LUT made in that blog post to work, the user must also change the NEW_VIS_FALSE_CURVE in goesdump/XRIT/Tools/Presets.cs. The LUT and contrast curve are currently in a dropbox link at the bottom of the blog post. I agree that goesdump (and/or the XRIT code) should have a simpler way to change LUTs and curves.

**Comment by racerxdl** [comment]
Done! Now there are two options in goesdump configurations that can load custom files  for LUT and Curve . The curve is a float array file, text plain. Like this:

```
0.000000, 0.008996, 0.017990, 0.026980, 0.035964, 0.044941, 0.053908, 0.062864, 0.071806, 0.080733, 0.089642, 0.098533, 0.107402, 0.116248, 0.125069, 0.133864,
0.142629, 0.151364, 0.160067, 0.168734, 0.177366, 0.185958, 0.194511, 0.203021, 0.211488, 0.219908, 0.228280, 0.236602, 0.244873, 0.253090, 0.261251, 0.269354,
0.277398, 0.285381, 0.293300, 0.301154, 0.308941, 0.316659, 0.324306, 0.331880, 0.339379, 0.346801, 0.354145, 0.361408, 0.368588, 0.375684, 0.382694, 0.389615,
0.396446, 0.403185, 0.409830, 0.416380, 0.422831, 0.429182, 0.435432, 0.441578, 0.448669, 0.454624, 0.460553, 0.466455, 0.472329, 0.478176, 0.483995, 0.489786,
0.495549, 0.501282, 0.506986, 0.512661, 0.518306, 0.523920, 0.529504, 0.535057, 0.540579, 0.546069, 0.551527, 0.556952, 0.562345, 0.567705, 0.573032, 0.578325,
0.583584, 0.588809, 0.593999, 0.599153, 0.604273, 0.609357, 0.614404, 0.619416, 0.624390, 0.629328, 0.634228, 0.639090, 0.643914, 0.648699, 0.653446, 0.658154,
0.662822, 0.667450, 0.672038, 0.676586, 0.681093, 0.685558, 0.689982, 0.694364, 0.698704, 0.703002, 0.707256, 0.711467, 0.715635, 0.719758, 0.723838, 0.727873,
0.731862, 0.735807, 0.739706, 0.743559, 0.747365, 0.751125, 0.754838, 0.758503, 0.762121, 0.765691, 0.769212, 0.772685, 0.776109, 0.779483, 0.782808, 0.786082,
0.789306, 0.792479, 0.795601, 0.798672, 0.801691, 0.804657, 0.807572, 0.810433, 0.813688, 0.816446, 0.819174, 0.821871, 0.824539, 0.827178, 0.829788, 0.832368,
0.834921, 0.837444, 0.839940, 0.842408, 0.844848, 0.847261, 0.849647, 0.852006, 0.854338, 0.856644, 0.858924, 0.861178, 0.863407, 0.865610, 0.867789, 0.869942,
0.872071, 0.874176, 0.876257, 0.878314, 0.880348, 0.882358, 0.884345, 0.886310, 0.888252, 0.890172, 0.892070, 0.893947, 0.895801, 0.897635, 0.899448, 0.901240,
0.903012, 0.904763, 0.906495, 0.908207, 0.909899, 0.911573, 0.913227, 0.914863, 0.916481, 0.918080, 0.919662, 0.921226, 0.922773, 0.924302, 0.925815, 0.927311,
0.928791, 0.930255, 0.931703, 0.933135, 0.934553, 0.935955, 0.937342, 0.938715, 0.940074, 0.941418, 0.942749, 0.944066, 0.945370, 0.946662, 0.947940, 0.949206,
0.950459, 0.951701, 0.952931, 0.954150, 0.955357, 0.956554, 0.957739, 0.958915, 0.960080, 0.961235, 0.962381, 0.963517, 0.964644, 0.965762, 0.966872, 0.967973,
0.969066, 0.970152, 0.971229, 0.972300, 0.973363, 0.974419, 0.975469, 0.976512, 0.977550, 0.978581, 0.979608, 0.980628, 0.981644, 0.982655, 0.983661, 0.984664,
0.985662, 0.986656, 0.987647, 0.988634, 0.989619, 0.990601, 0.991580, 0.992558, 0.993533, 0.994506, 0.995478, 0.996449, 0.997419, 0.998389, 0.999357, 1.000000,

``

**Comment by n2cr** [comment]
Pulled TestingFeatures branch and built.  Noticed that executable has new name "GOES Dumper.exe" vs. old "goesdump.exe".   Ran executable and web page shows signal and graph status but configuration page does not display any parameters, just heading.  Same with Firefox under Ubuntu and IE,Chrome,Firefox under Windows.

**Comment by racerxdl** [comment]
@n2cr try it now :D

**Comment by racerxdl** [comment]
Just a sec, let me upload the new web package (its a web package bug)

**Comment by racerxdl** [comment]
Try the web gui from here: https://github.com/opensatelliteproject/goesdump/releases/tag/1.3.6489

**Comment by n2cr** [comment]
Unpacked file into web directory.  Need to use Internet Explorer in order to have changes to configuration saved (this is an old problem).  Still don't see any content on config page when using IE.  OK with Firefox on Windows but changes are not saved.

**Comment by n2cr** [comment]
Created new config.db and used DB Browser for SQLite to manually set desired values.  Running now.

Note to others that the curve file contained in the wx-star.com zip file is in the wrong format and can not be used directly.  The "f" characters after each number need to be removed.

**Comment by racerxdl** [comment]
I can make it support with f in the float, just a sec.

**Comment by racerxdl** [comment]
Now it should work.

**Comment by n2cr** [comment]
First false color image looks great!

**Comment by racerxdl** [comment]
Nice! That's great :D

**Comment by hdoverobinson** [comment]
I am wx-star.com and I will soon adjust the formats I put up to whatever best suits OSP.

**Comment by hdoverobinson** [comment]
The curve format I used was mirrored from what Lucas had in previous goesdump version
